"""add branding fields to app_settings

Revision ID: 65bc75ae5543
Revises: ee5b7a989298
Create Date: 2026-06-03 15:08:22.241895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65bc75ae5543'
down_revision: Union[str, None] = 'ee5b7a989298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('branding_text', sa.String(), nullable=True))
    op.add_column('app_settings', sa.Column('sub_text', sa.String(), nullable=True))
    
    # Fill existing rows with defaults
    op.execute("UPDATE app_settings SET branding_text = 'Empowering Digital Enterprise' WHERE branding_text IS NULL")
    op.execute("UPDATE app_settings SET sub_text = 'Experience the next generation of multi-application management with our secure, unified platform.' WHERE sub_text IS NULL")

    # Set to nullable=False
    op.alter_column('app_settings', 'branding_text', nullable=False)
    op.alter_column('app_settings', 'sub_text', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'sub_text')
    op.drop_column('app_settings', 'branding_text')
    # ### end Alembic commands ###
